const FETCH_MOVIE_LIST_REQUEST = "FETCH_MOVIE_LIST_REQUEST";
const FETCH_MOVIE_LIST_SUCCESS = "FETCH_MOVIE_LIST_SUCCESS";
const FETCH_MOVIE_LIST_FAILURE = "FETCH_MOVIE_LIST_FAILURE";

export {
  FETCH_MOVIE_LIST_REQUEST,
  FETCH_MOVIE_LIST_SUCCESS,
  FETCH_MOVIE_LIST_FAILURE,
};
